// Autogenerated from Pigeon (v25.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class LibVlcInput (
  val options: List<String>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LibVlcInput {
      val options = pigeonVar_list[0] as List<String>?
      return LibVlcInput(options)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      options,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LibVlcInput) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LibVlcOutput (
  val libVlcId: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LibVlcOutput {
      val libVlcId = pigeonVar_list[0] as Long?
      return LibVlcOutput(libVlcId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      libVlcId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LibVlcOutput) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaInput (
  val libVlcId: Long? = null,
  val dataSourceType: Long? = null,
  val dataSourceValue: String? = null,
  val packageName: String? = null,
  val hwAcc: Long? = null,
  val options: List<String>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaInput {
      val libVlcId = pigeonVar_list[0] as Long?
      val dataSourceType = pigeonVar_list[1] as Long?
      val dataSourceValue = pigeonVar_list[2] as String?
      val packageName = pigeonVar_list[3] as String?
      val hwAcc = pigeonVar_list[4] as Long?
      val options = pigeonVar_list[5] as List<String>?
      return MediaInput(libVlcId, dataSourceType, dataSourceValue, packageName, hwAcc, options)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      libVlcId,
      dataSourceType,
      dataSourceValue,
      packageName,
      hwAcc,
      options,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MediaInput) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaOutput (
  val mediaId: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaOutput {
      val mediaId = pigeonVar_list[0] as Long?
      return MediaOutput(mediaId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mediaId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MediaOutput) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaPlayerInput (
  val libVlcId: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaPlayerInput {
      val libVlcId = pigeonVar_list[0] as Long?
      return MediaPlayerInput(libVlcId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      libVlcId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MediaPlayerInput) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaPlayerOutput (
  val mediaPlayerId: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaPlayerOutput {
      val mediaPlayerId = pigeonVar_list[0] as Long?
      return MediaPlayerOutput(mediaPlayerId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mediaPlayerId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MediaPlayerOutput) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LibVlcInput.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LibVlcOutput.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaInput.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaOutput.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaPlayerInput.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaPlayerOutput.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LibVlcInput -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is LibVlcOutput -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is MediaInput -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is MediaOutput -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is MediaPlayerInput -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is MediaPlayerOutput -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface VlcApi {
  /** LibVLC */
  fun createLibVlc(input: LibVlcInput, callback: (Result<LibVlcOutput>) -> Unit)
  fun disposeLibVlc(libVlcId: Long, callback: (Result<Boolean>) -> Unit)
  /** Media */
  fun createMedia(input: MediaInput, callback: (Result<MediaOutput>) -> Unit)
  fun setMediaEventListener(mediaId: Long, callback: (Result<Boolean>) -> Unit)
  fun mediaParseAsync(mediaId: Long, callback: (Result<Boolean>) -> Unit)
  fun disposeMedia(mediaId: Long, callback: (Result<Boolean>) -> Unit)
  /** MediaPlayer */
  fun createMediaPlayer(input: MediaPlayerInput, callback: (Result<MediaPlayerOutput>) -> Unit)
  fun disposeMediaPlayer(mediaPlayerId: Long, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by VlcApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `VlcApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VlcApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.createLibVlc$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val inputArg = args[0] as LibVlcInput
            api.createLibVlc(inputArg) { result: Result<LibVlcOutput> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.disposeLibVlc$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val libVlcIdArg = args[0] as Long
            api.disposeLibVlc(libVlcIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.createMedia$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val inputArg = args[0] as MediaInput
            api.createMedia(inputArg) { result: Result<MediaOutput> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.setMediaEventListener$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mediaIdArg = args[0] as Long
            api.setMediaEventListener(mediaIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.mediaParseAsync$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mediaIdArg = args[0] as Long
            api.mediaParseAsync(mediaIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.disposeMedia$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mediaIdArg = args[0] as Long
            api.disposeMedia(mediaIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.createMediaPlayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val inputArg = args[0] as MediaPlayerInput
            api.createMediaPlayer(inputArg) { result: Result<MediaPlayerOutput> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.disposeMediaPlayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mediaPlayerIdArg = args[0] as Long
            api.disposeMediaPlayer(mediaPlayerIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class VlcFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by VlcFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onMediaEvent(mediaIdArg: Long, eventArg: Long, callback: (Result<Boolean>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcFlutterApi.onMediaEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(mediaIdArg, eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as Boolean
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
