// Autogenerated from Pigeon (v25.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct LibVlcInput: Hashable {
  var options: [String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LibVlcInput? {
    let options: [String]? = nilOrValue(pigeonVar_list[0])

    return LibVlcInput(
      options: options
    )
  }
  func toList() -> [Any?] {
    return [
      options
    ]
  }
  static func == (lhs: LibVlcInput, rhs: LibVlcInput) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LibVlcOutput: Hashable {
  var libVlcId: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LibVlcOutput? {
    let libVlcId: Int64? = nilOrValue(pigeonVar_list[0])

    return LibVlcOutput(
      libVlcId: libVlcId
    )
  }
  func toList() -> [Any?] {
    return [
      libVlcId
    ]
  }
  static func == (lhs: LibVlcOutput, rhs: LibVlcOutput) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MediaInput: Hashable {
  var libVlcId: Int64? = nil
  var dataSourceType: Int64? = nil
  var dataSourceValue: String? = nil
  var packageName: String? = nil
  var hwAcc: Int64? = nil
  var options: [String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaInput? {
    let libVlcId: Int64? = nilOrValue(pigeonVar_list[0])
    let dataSourceType: Int64? = nilOrValue(pigeonVar_list[1])
    let dataSourceValue: String? = nilOrValue(pigeonVar_list[2])
    let packageName: String? = nilOrValue(pigeonVar_list[3])
    let hwAcc: Int64? = nilOrValue(pigeonVar_list[4])
    let options: [String]? = nilOrValue(pigeonVar_list[5])

    return MediaInput(
      libVlcId: libVlcId,
      dataSourceType: dataSourceType,
      dataSourceValue: dataSourceValue,
      packageName: packageName,
      hwAcc: hwAcc,
      options: options
    )
  }
  func toList() -> [Any?] {
    return [
      libVlcId,
      dataSourceType,
      dataSourceValue,
      packageName,
      hwAcc,
      options,
    ]
  }
  static func == (lhs: MediaInput, rhs: MediaInput) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MediaOutput: Hashable {
  var mediaId: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaOutput? {
    let mediaId: Int64? = nilOrValue(pigeonVar_list[0])

    return MediaOutput(
      mediaId: mediaId
    )
  }
  func toList() -> [Any?] {
    return [
      mediaId
    ]
  }
  static func == (lhs: MediaOutput, rhs: MediaOutput) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MediaVideoTrack: Hashable {
  var duration: Int64? = nil
  var height: Int64? = nil
  var width: Int64? = nil
  var sarNum: Int64? = nil
  var sarDen: Int64? = nil
  var frameRateNum: Int64? = nil
  var frameRateDen: Int64? = nil
  var orientation: Int64? = nil
  var projection: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaVideoTrack? {
    let duration: Int64? = nilOrValue(pigeonVar_list[0])
    let height: Int64? = nilOrValue(pigeonVar_list[1])
    let width: Int64? = nilOrValue(pigeonVar_list[2])
    let sarNum: Int64? = nilOrValue(pigeonVar_list[3])
    let sarDen: Int64? = nilOrValue(pigeonVar_list[4])
    let frameRateNum: Int64? = nilOrValue(pigeonVar_list[5])
    let frameRateDen: Int64? = nilOrValue(pigeonVar_list[6])
    let orientation: Int64? = nilOrValue(pigeonVar_list[7])
    let projection: Int64? = nilOrValue(pigeonVar_list[8])

    return MediaVideoTrack(
      duration: duration,
      height: height,
      width: width,
      sarNum: sarNum,
      sarDen: sarDen,
      frameRateNum: frameRateNum,
      frameRateDen: frameRateDen,
      orientation: orientation,
      projection: projection
    )
  }
  func toList() -> [Any?] {
    return [
      duration,
      height,
      width,
      sarNum,
      sarDen,
      frameRateNum,
      frameRateDen,
      orientation,
      projection,
    ]
  }
  static func == (lhs: MediaVideoTrack, rhs: MediaVideoTrack) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MediaPlayerInput: Hashable {
  var libVlcId: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaPlayerInput? {
    let libVlcId: Int64? = nilOrValue(pigeonVar_list[0])

    return MediaPlayerInput(
      libVlcId: libVlcId
    )
  }
  func toList() -> [Any?] {
    return [
      libVlcId
    ]
  }
  static func == (lhs: MediaPlayerInput, rhs: MediaPlayerInput) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MediaPlayerOutput: Hashable {
  var mediaPlayerId: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaPlayerOutput? {
    let mediaPlayerId: Int64? = nilOrValue(pigeonVar_list[0])

    return MediaPlayerOutput(
      mediaPlayerId: mediaPlayerId
    )
  }
  func toList() -> [Any?] {
    return [
      mediaPlayerId
    ]
  }
  static func == (lhs: MediaPlayerOutput, rhs: MediaPlayerOutput) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return LibVlcInput.fromList(self.readValue() as! [Any?])
    case 130:
      return LibVlcOutput.fromList(self.readValue() as! [Any?])
    case 131:
      return MediaInput.fromList(self.readValue() as! [Any?])
    case 132:
      return MediaOutput.fromList(self.readValue() as! [Any?])
    case 133:
      return MediaVideoTrack.fromList(self.readValue() as! [Any?])
    case 134:
      return MediaPlayerInput.fromList(self.readValue() as! [Any?])
    case 135:
      return MediaPlayerOutput.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? LibVlcInput {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? LibVlcOutput {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? MediaInput {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? MediaOutput {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? MediaVideoTrack {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? MediaPlayerInput {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? MediaPlayerOutput {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VlcApi {
  /// LibVLC
  func createLibVlc(input: LibVlcInput, completion: @escaping (Result<LibVlcOutput, Error>) -> Void)
  func disposeLibVlc(libVlcId: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Media
  func createMedia(input: MediaInput, completion: @escaping (Result<MediaOutput, Error>) -> Void)
  func setMediaEventListener(mediaId: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
  func mediaParseAsync(mediaId: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
  func mediaGetVideoTrack(mediaId: Int64, completion: @escaping (Result<MediaVideoTrack, Error>) -> Void)
  func disposeMedia(mediaId: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
  /// MediaPlayer
  func createMediaPlayer(input: MediaPlayerInput, completion: @escaping (Result<MediaPlayerOutput, Error>) -> Void)
  func disposeMediaPlayer(mediaPlayerId: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VlcApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `VlcApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VlcApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// LibVLC
    let createLibVlcChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.createLibVlc\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createLibVlcChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let inputArg = args[0] as! LibVlcInput
        api.createLibVlc(input: inputArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createLibVlcChannel.setMessageHandler(nil)
    }
    let disposeLibVlcChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.disposeLibVlc\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeLibVlcChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let libVlcIdArg = args[0] as! Int64
        api.disposeLibVlc(libVlcId: libVlcIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeLibVlcChannel.setMessageHandler(nil)
    }
    /// Media
    let createMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.createMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createMediaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let inputArg = args[0] as! MediaInput
        api.createMedia(input: inputArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createMediaChannel.setMessageHandler(nil)
    }
    let setMediaEventListenerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.setMediaEventListener\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMediaEventListenerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mediaIdArg = args[0] as! Int64
        api.setMediaEventListener(mediaId: mediaIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setMediaEventListenerChannel.setMessageHandler(nil)
    }
    let mediaParseAsyncChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.mediaParseAsync\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      mediaParseAsyncChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mediaIdArg = args[0] as! Int64
        api.mediaParseAsync(mediaId: mediaIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      mediaParseAsyncChannel.setMessageHandler(nil)
    }
    let mediaGetVideoTrackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.mediaGetVideoTrack\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      mediaGetVideoTrackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mediaIdArg = args[0] as! Int64
        api.mediaGetVideoTrack(mediaId: mediaIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      mediaGetVideoTrackChannel.setMessageHandler(nil)
    }
    let disposeMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.disposeMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeMediaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mediaIdArg = args[0] as! Int64
        api.disposeMedia(mediaId: mediaIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeMediaChannel.setMessageHandler(nil)
    }
    /// MediaPlayer
    let createMediaPlayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.createMediaPlayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createMediaPlayerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let inputArg = args[0] as! MediaPlayerInput
        api.createMediaPlayer(input: inputArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createMediaPlayerChannel.setMessageHandler(nil)
    }
    let disposeMediaPlayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.disposeMediaPlayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeMediaPlayerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mediaPlayerIdArg = args[0] as! Int64
        api.disposeMediaPlayer(mediaPlayerId: mediaPlayerIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeMediaPlayerChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol VlcFlutterApiProtocol {
  func onMediaEvent(mediaId mediaIdArg: Int64, event eventArg: Int64, completion: @escaping (Result<Bool, PigeonError>) -> Void)
}
class VlcFlutterApi: VlcFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onMediaEvent(mediaId mediaIdArg: Int64, event eventArg: Int64, completion: @escaping (Result<Bool, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.com.shinezzl.vlc_player.VlcFlutterApi.onMediaEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([mediaIdArg, eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! Bool
        completion(.success(result))
      }
    }
  }
}
