// Autogenerated from Pigeon (v25.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "messages.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static FlutterError *createConnectionError(NSString *channelName) {
  return [FlutterError errorWithCode:@"channel-error" message:[NSString stringWithFormat:@"%@/%@/%@", @"Unable to establish connection on channel: '", channelName, @"'."] details:@""];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface VLC_PLAYERLibVlcInput ()
+ (VLC_PLAYERLibVlcInput *)fromList:(NSArray<id> *)list;
+ (nullable VLC_PLAYERLibVlcInput *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface VLC_PLAYERLibVlcOutput ()
+ (VLC_PLAYERLibVlcOutput *)fromList:(NSArray<id> *)list;
+ (nullable VLC_PLAYERLibVlcOutput *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface VLC_PLAYERMediaInput ()
+ (VLC_PLAYERMediaInput *)fromList:(NSArray<id> *)list;
+ (nullable VLC_PLAYERMediaInput *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface VLC_PLAYERMediaOutput ()
+ (VLC_PLAYERMediaOutput *)fromList:(NSArray<id> *)list;
+ (nullable VLC_PLAYERMediaOutput *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface VLC_PLAYERMediaVideoTrack ()
+ (VLC_PLAYERMediaVideoTrack *)fromList:(NSArray<id> *)list;
+ (nullable VLC_PLAYERMediaVideoTrack *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface VLC_PLAYERMediaPlayerInput ()
+ (VLC_PLAYERMediaPlayerInput *)fromList:(NSArray<id> *)list;
+ (nullable VLC_PLAYERMediaPlayerInput *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface VLC_PLAYERMediaPlayerOutput ()
+ (VLC_PLAYERMediaPlayerOutput *)fromList:(NSArray<id> *)list;
+ (nullable VLC_PLAYERMediaPlayerOutput *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface VLC_PLAYERVideoViewOutput ()
+ (VLC_PLAYERVideoViewOutput *)fromList:(NSArray<id> *)list;
+ (nullable VLC_PLAYERVideoViewOutput *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation VLC_PLAYERLibVlcInput
+ (instancetype)makeWithOptions:(nullable NSArray<NSString *> *)options {
  VLC_PLAYERLibVlcInput* pigeonResult = [[VLC_PLAYERLibVlcInput alloc] init];
  pigeonResult.options = options;
  return pigeonResult;
}
+ (VLC_PLAYERLibVlcInput *)fromList:(NSArray<id> *)list {
  VLC_PLAYERLibVlcInput *pigeonResult = [[VLC_PLAYERLibVlcInput alloc] init];
  pigeonResult.options = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable VLC_PLAYERLibVlcInput *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [VLC_PLAYERLibVlcInput fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.options ?: [NSNull null],
  ];
}
@end

@implementation VLC_PLAYERLibVlcOutput
+ (instancetype)makeWithLibVlcId:(nullable NSNumber *)libVlcId {
  VLC_PLAYERLibVlcOutput* pigeonResult = [[VLC_PLAYERLibVlcOutput alloc] init];
  pigeonResult.libVlcId = libVlcId;
  return pigeonResult;
}
+ (VLC_PLAYERLibVlcOutput *)fromList:(NSArray<id> *)list {
  VLC_PLAYERLibVlcOutput *pigeonResult = [[VLC_PLAYERLibVlcOutput alloc] init];
  pigeonResult.libVlcId = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable VLC_PLAYERLibVlcOutput *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [VLC_PLAYERLibVlcOutput fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.libVlcId ?: [NSNull null],
  ];
}
@end

@implementation VLC_PLAYERMediaInput
+ (instancetype)makeWithLibVlcId:(nullable NSNumber *)libVlcId
    dataSourceType:(nullable NSNumber *)dataSourceType
    dataSourceValue:(nullable NSString *)dataSourceValue
    packageName:(nullable NSString *)packageName
    hwAcc:(nullable NSNumber *)hwAcc
    options:(nullable NSArray<NSString *> *)options {
  VLC_PLAYERMediaInput* pigeonResult = [[VLC_PLAYERMediaInput alloc] init];
  pigeonResult.libVlcId = libVlcId;
  pigeonResult.dataSourceType = dataSourceType;
  pigeonResult.dataSourceValue = dataSourceValue;
  pigeonResult.packageName = packageName;
  pigeonResult.hwAcc = hwAcc;
  pigeonResult.options = options;
  return pigeonResult;
}
+ (VLC_PLAYERMediaInput *)fromList:(NSArray<id> *)list {
  VLC_PLAYERMediaInput *pigeonResult = [[VLC_PLAYERMediaInput alloc] init];
  pigeonResult.libVlcId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.dataSourceType = GetNullableObjectAtIndex(list, 1);
  pigeonResult.dataSourceValue = GetNullableObjectAtIndex(list, 2);
  pigeonResult.packageName = GetNullableObjectAtIndex(list, 3);
  pigeonResult.hwAcc = GetNullableObjectAtIndex(list, 4);
  pigeonResult.options = GetNullableObjectAtIndex(list, 5);
  return pigeonResult;
}
+ (nullable VLC_PLAYERMediaInput *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [VLC_PLAYERMediaInput fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.libVlcId ?: [NSNull null],
    self.dataSourceType ?: [NSNull null],
    self.dataSourceValue ?: [NSNull null],
    self.packageName ?: [NSNull null],
    self.hwAcc ?: [NSNull null],
    self.options ?: [NSNull null],
  ];
}
@end

@implementation VLC_PLAYERMediaOutput
+ (instancetype)makeWithMediaId:(nullable NSNumber *)mediaId {
  VLC_PLAYERMediaOutput* pigeonResult = [[VLC_PLAYERMediaOutput alloc] init];
  pigeonResult.mediaId = mediaId;
  return pigeonResult;
}
+ (VLC_PLAYERMediaOutput *)fromList:(NSArray<id> *)list {
  VLC_PLAYERMediaOutput *pigeonResult = [[VLC_PLAYERMediaOutput alloc] init];
  pigeonResult.mediaId = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable VLC_PLAYERMediaOutput *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [VLC_PLAYERMediaOutput fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.mediaId ?: [NSNull null],
  ];
}
@end

@implementation VLC_PLAYERMediaVideoTrack
+ (instancetype)makeWithDuration:(nullable NSNumber *)duration
    height:(nullable NSNumber *)height
    width:(nullable NSNumber *)width
    sarNum:(nullable NSNumber *)sarNum
    sarDen:(nullable NSNumber *)sarDen
    frameRateNum:(nullable NSNumber *)frameRateNum
    frameRateDen:(nullable NSNumber *)frameRateDen
    orientation:(nullable NSNumber *)orientation
    projection:(nullable NSNumber *)projection {
  VLC_PLAYERMediaVideoTrack* pigeonResult = [[VLC_PLAYERMediaVideoTrack alloc] init];
  pigeonResult.duration = duration;
  pigeonResult.height = height;
  pigeonResult.width = width;
  pigeonResult.sarNum = sarNum;
  pigeonResult.sarDen = sarDen;
  pigeonResult.frameRateNum = frameRateNum;
  pigeonResult.frameRateDen = frameRateDen;
  pigeonResult.orientation = orientation;
  pigeonResult.projection = projection;
  return pigeonResult;
}
+ (VLC_PLAYERMediaVideoTrack *)fromList:(NSArray<id> *)list {
  VLC_PLAYERMediaVideoTrack *pigeonResult = [[VLC_PLAYERMediaVideoTrack alloc] init];
  pigeonResult.duration = GetNullableObjectAtIndex(list, 0);
  pigeonResult.height = GetNullableObjectAtIndex(list, 1);
  pigeonResult.width = GetNullableObjectAtIndex(list, 2);
  pigeonResult.sarNum = GetNullableObjectAtIndex(list, 3);
  pigeonResult.sarDen = GetNullableObjectAtIndex(list, 4);
  pigeonResult.frameRateNum = GetNullableObjectAtIndex(list, 5);
  pigeonResult.frameRateDen = GetNullableObjectAtIndex(list, 6);
  pigeonResult.orientation = GetNullableObjectAtIndex(list, 7);
  pigeonResult.projection = GetNullableObjectAtIndex(list, 8);
  return pigeonResult;
}
+ (nullable VLC_PLAYERMediaVideoTrack *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [VLC_PLAYERMediaVideoTrack fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.duration ?: [NSNull null],
    self.height ?: [NSNull null],
    self.width ?: [NSNull null],
    self.sarNum ?: [NSNull null],
    self.sarDen ?: [NSNull null],
    self.frameRateNum ?: [NSNull null],
    self.frameRateDen ?: [NSNull null],
    self.orientation ?: [NSNull null],
    self.projection ?: [NSNull null],
  ];
}
@end

@implementation VLC_PLAYERMediaPlayerInput
+ (instancetype)makeWithLibVlcId:(nullable NSNumber *)libVlcId {
  VLC_PLAYERMediaPlayerInput* pigeonResult = [[VLC_PLAYERMediaPlayerInput alloc] init];
  pigeonResult.libVlcId = libVlcId;
  return pigeonResult;
}
+ (VLC_PLAYERMediaPlayerInput *)fromList:(NSArray<id> *)list {
  VLC_PLAYERMediaPlayerInput *pigeonResult = [[VLC_PLAYERMediaPlayerInput alloc] init];
  pigeonResult.libVlcId = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable VLC_PLAYERMediaPlayerInput *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [VLC_PLAYERMediaPlayerInput fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.libVlcId ?: [NSNull null],
  ];
}
@end

@implementation VLC_PLAYERMediaPlayerOutput
+ (instancetype)makeWithMediaPlayerId:(nullable NSNumber *)mediaPlayerId {
  VLC_PLAYERMediaPlayerOutput* pigeonResult = [[VLC_PLAYERMediaPlayerOutput alloc] init];
  pigeonResult.mediaPlayerId = mediaPlayerId;
  return pigeonResult;
}
+ (VLC_PLAYERMediaPlayerOutput *)fromList:(NSArray<id> *)list {
  VLC_PLAYERMediaPlayerOutput *pigeonResult = [[VLC_PLAYERMediaPlayerOutput alloc] init];
  pigeonResult.mediaPlayerId = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable VLC_PLAYERMediaPlayerOutput *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [VLC_PLAYERMediaPlayerOutput fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.mediaPlayerId ?: [NSNull null],
  ];
}
@end

@implementation VLC_PLAYERVideoViewOutput
+ (instancetype)makeWithObjectId:(nullable NSNumber *)objectId
    textureId:(nullable NSNumber *)textureId {
  VLC_PLAYERVideoViewOutput* pigeonResult = [[VLC_PLAYERVideoViewOutput alloc] init];
  pigeonResult.objectId = objectId;
  pigeonResult.textureId = textureId;
  return pigeonResult;
}
+ (VLC_PLAYERVideoViewOutput *)fromList:(NSArray<id> *)list {
  VLC_PLAYERVideoViewOutput *pigeonResult = [[VLC_PLAYERVideoViewOutput alloc] init];
  pigeonResult.objectId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.textureId = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable VLC_PLAYERVideoViewOutput *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [VLC_PLAYERVideoViewOutput fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.objectId ?: [NSNull null],
    self.textureId ?: [NSNull null],
  ];
}
@end

@interface VLC_PLAYERMessagesPigeonCodecReader : FlutterStandardReader
@end
@implementation VLC_PLAYERMessagesPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: 
      return [VLC_PLAYERLibVlcInput fromList:[self readValue]];
    case 130: 
      return [VLC_PLAYERLibVlcOutput fromList:[self readValue]];
    case 131: 
      return [VLC_PLAYERMediaInput fromList:[self readValue]];
    case 132: 
      return [VLC_PLAYERMediaOutput fromList:[self readValue]];
    case 133: 
      return [VLC_PLAYERMediaVideoTrack fromList:[self readValue]];
    case 134: 
      return [VLC_PLAYERMediaPlayerInput fromList:[self readValue]];
    case 135: 
      return [VLC_PLAYERMediaPlayerOutput fromList:[self readValue]];
    case 136: 
      return [VLC_PLAYERVideoViewOutput fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface VLC_PLAYERMessagesPigeonCodecWriter : FlutterStandardWriter
@end
@implementation VLC_PLAYERMessagesPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[VLC_PLAYERLibVlcInput class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[VLC_PLAYERLibVlcOutput class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[VLC_PLAYERMediaInput class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[VLC_PLAYERMediaOutput class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[VLC_PLAYERMediaVideoTrack class]]) {
    [self writeByte:133];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[VLC_PLAYERMediaPlayerInput class]]) {
    [self writeByte:134];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[VLC_PLAYERMediaPlayerOutput class]]) {
    [self writeByte:135];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[VLC_PLAYERVideoViewOutput class]]) {
    [self writeByte:136];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface VLC_PLAYERMessagesPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation VLC_PLAYERMessagesPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[VLC_PLAYERMessagesPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[VLC_PLAYERMessagesPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *VLC_PLAYERGetMessagesCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    VLC_PLAYERMessagesPigeonCodecReaderWriter *readerWriter = [[VLC_PLAYERMessagesPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpVLC_PLAYERVlcApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<VLC_PLAYERVlcApi> *api) {
  SetUpVLC_PLAYERVlcApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpVLC_PLAYERVlcApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<VLC_PLAYERVlcApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  /// LibVLC
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.createLibVlc", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:VLC_PLAYERGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createLibVlcInput:completion:)], @"VLC_PLAYERVlcApi api (%@) doesn't respond to @selector(createLibVlcInput:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        VLC_PLAYERLibVlcInput *arg_input = GetNullableObjectAtIndex(args, 0);
        [api createLibVlcInput:arg_input completion:^(VLC_PLAYERLibVlcOutput *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.disposeLibVlc", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:VLC_PLAYERGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(disposeLibVlcLibVlcId:completion:)], @"VLC_PLAYERVlcApi api (%@) doesn't respond to @selector(disposeLibVlcLibVlcId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_libVlcId = [GetNullableObjectAtIndex(args, 0) integerValue];
        [api disposeLibVlcLibVlcId:arg_libVlcId completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Media
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.createMedia", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:VLC_PLAYERGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createMediaInput:completion:)], @"VLC_PLAYERVlcApi api (%@) doesn't respond to @selector(createMediaInput:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        VLC_PLAYERMediaInput *arg_input = GetNullableObjectAtIndex(args, 0);
        [api createMediaInput:arg_input completion:^(VLC_PLAYERMediaOutput *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.setMediaEventListener", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:VLC_PLAYERGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setMediaEventListenerMediaId:completion:)], @"VLC_PLAYERVlcApi api (%@) doesn't respond to @selector(setMediaEventListenerMediaId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_mediaId = [GetNullableObjectAtIndex(args, 0) integerValue];
        [api setMediaEventListenerMediaId:arg_mediaId completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.mediaParseAsync", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:VLC_PLAYERGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(mediaParseAsyncMediaId:completion:)], @"VLC_PLAYERVlcApi api (%@) doesn't respond to @selector(mediaParseAsyncMediaId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_mediaId = [GetNullableObjectAtIndex(args, 0) integerValue];
        [api mediaParseAsyncMediaId:arg_mediaId completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.mediaGetVideoTrack", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:VLC_PLAYERGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(mediaGetVideoTrackMediaId:completion:)], @"VLC_PLAYERVlcApi api (%@) doesn't respond to @selector(mediaGetVideoTrackMediaId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_mediaId = [GetNullableObjectAtIndex(args, 0) integerValue];
        [api mediaGetVideoTrackMediaId:arg_mediaId completion:^(VLC_PLAYERMediaVideoTrack *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.disposeMedia", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:VLC_PLAYERGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(disposeMediaMediaId:completion:)], @"VLC_PLAYERVlcApi api (%@) doesn't respond to @selector(disposeMediaMediaId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_mediaId = [GetNullableObjectAtIndex(args, 0) integerValue];
        [api disposeMediaMediaId:arg_mediaId completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// MediaPlayer
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.createMediaPlayer", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:VLC_PLAYERGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createMediaPlayerInput:completion:)], @"VLC_PLAYERVlcApi api (%@) doesn't respond to @selector(createMediaPlayerInput:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        VLC_PLAYERMediaPlayerInput *arg_input = GetNullableObjectAtIndex(args, 0);
        [api createMediaPlayerInput:arg_input completion:^(VLC_PLAYERMediaPlayerOutput *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.mediaPlayerSetMedia", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:VLC_PLAYERGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(mediaPlayerSetMediaMediaPlayerId:mediaId:completion:)], @"VLC_PLAYERVlcApi api (%@) doesn't respond to @selector(mediaPlayerSetMediaMediaPlayerId:mediaId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_mediaPlayerId = [GetNullableObjectAtIndex(args, 0) integerValue];
        NSInteger arg_mediaId = [GetNullableObjectAtIndex(args, 1) integerValue];
        [api mediaPlayerSetMediaMediaPlayerId:arg_mediaPlayerId mediaId:arg_mediaId completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.mediaPlayerAttachVideoView", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:VLC_PLAYERGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(mediaPlayerAttachVideoViewMediaPlayerId:videoViewId:completion:)], @"VLC_PLAYERVlcApi api (%@) doesn't respond to @selector(mediaPlayerAttachVideoViewMediaPlayerId:videoViewId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_mediaPlayerId = [GetNullableObjectAtIndex(args, 0) integerValue];
        NSInteger arg_videoViewId = [GetNullableObjectAtIndex(args, 1) integerValue];
        [api mediaPlayerAttachVideoViewMediaPlayerId:arg_mediaPlayerId videoViewId:arg_videoViewId completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.mediaPlayerPlay", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:VLC_PLAYERGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(mediaPlayerPlayMediaPlayerId:completion:)], @"VLC_PLAYERVlcApi api (%@) doesn't respond to @selector(mediaPlayerPlayMediaPlayerId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_mediaPlayerId = [GetNullableObjectAtIndex(args, 0) integerValue];
        [api mediaPlayerPlayMediaPlayerId:arg_mediaPlayerId completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.disposeMediaPlayer", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:VLC_PLAYERGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(disposeMediaPlayerMediaPlayerId:completion:)], @"VLC_PLAYERVlcApi api (%@) doesn't respond to @selector(disposeMediaPlayerMediaPlayerId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_mediaPlayerId = [GetNullableObjectAtIndex(args, 0) integerValue];
        [api disposeMediaPlayerMediaPlayerId:arg_mediaPlayerId completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Video View
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.createVideoView", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:VLC_PLAYERGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createVideoViewWithCompletion:)], @"VLC_PLAYERVlcApi api (%@) doesn't respond to @selector(createVideoViewWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api createVideoViewWithCompletion:^(VLC_PLAYERVideoViewOutput *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.videoViewSetDefaultBufferSize", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:VLC_PLAYERGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(videoViewSetDefaultBufferSizeVideoViewId:width:height:completion:)], @"VLC_PLAYERVlcApi api (%@) doesn't respond to @selector(videoViewSetDefaultBufferSizeVideoViewId:width:height:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_videoViewId = [GetNullableObjectAtIndex(args, 0) integerValue];
        NSInteger arg_width = [GetNullableObjectAtIndex(args, 1) integerValue];
        NSInteger arg_height = [GetNullableObjectAtIndex(args, 2) integerValue];
        [api videoViewSetDefaultBufferSizeVideoViewId:arg_videoViewId width:arg_width height:arg_height completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcApi.disposeVideoView", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:VLC_PLAYERGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(disposeVideoViewVideoViewId:completion:)], @"VLC_PLAYERVlcApi api (%@) doesn't respond to @selector(disposeVideoViewVideoViewId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_videoViewId = [GetNullableObjectAtIndex(args, 0) integerValue];
        [api disposeVideoViewVideoViewId:arg_videoViewId completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface VLC_PLAYERVlcFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@property(nonatomic, strong) NSString *messageChannelSuffix;
@end

@implementation VLC_PLAYERVlcFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  return [self initWithBinaryMessenger:binaryMessenger messageChannelSuffix:@""];
}
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger messageChannelSuffix:(nullable NSString*)messageChannelSuffix{
  self = [self init];
  if (self) {
    _binaryMessenger = binaryMessenger;
    _messageChannelSuffix = [messageChannelSuffix length] == 0 ? @"" : [NSString stringWithFormat: @".%@", messageChannelSuffix];
  }
  return self;
}
- (void)onMediaEventMediaId:(NSInteger)arg_mediaId event:(NSInteger)arg_event completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.com.shinezzl.vlc_player.VlcFlutterApi.onMediaEvent", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:VLC_PLAYERGetMessagesCodec()];
  [channel sendMessage:@[@(arg_mediaId), @(arg_event)] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion(nil, [FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        NSNumber *output = reply[0] == [NSNull null] ? nil : reply[0];
        completion(output, nil);
      }
    } else {
      completion(nil, createConnectionError(channelName));
    } 
  }];
}
@end

